import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
const script=path.resolve("tools/release/validate-promotion-request.mjs"); const sha=(v)=>createHash("sha256").update(v).digest("hex");
test("request의 raw evidence hash와 full candidate identity를 검증한다",()=>{const f=fixture();try{assert.equal(run(f).status,0);f.request.candidate.dataVersion="other";writeFileSync(f.requestPath,JSON.stringify(f.request));assert.notEqual(run(f).status,0);}finally{f.cleanup();}});
test("unknown request key와 compatibility hash mismatch를 거부한다",()=>{const f=fixture();try{f.request.extra=true;writeFileSync(f.requestPath,JSON.stringify(f.request));assert.notEqual(run(f).status,0);f.request=JSON.parse(f.requestBytes);writeFileSync(f.requestPath,JSON.stringify(f.request));writeFileSync(f.compatibilityPath,"changed");assert.notEqual(run(f).status,0);}finally{f.cleanup();}});
function fixture(){const root=mkdtempSync(path.join(os.tmpdir(),"promotion-validate-"));const inventory={schemaVersion:1,artifactKind:"datapack-candidate-inventory",entries:[]};const ib=Buffer.from(JSON.stringify(inventory));const component={schemaVersion:1,component:"data",repository:"AquilaXk/easysubway",gitSha:"a".repeat(40),workflowRunId:"123",dataVersion:"1",releaseSequence:1,manifestSha256:"b".repeat(64),provenance:{sourceSnapshotSetHash:"c".repeat(64)},artifactInventorySha256:sha(ib),contractVersion:"datapack-contract-v3",issueRef:"AquilaXk/easysubway#2699"};const compatibility=Buffer.from("compatibility");const approval=Buffer.from(JSON.stringify([{state:"approved",environments:[{name:"datapack-promotion"}],user:{login:"AquilaXk"}}]));const request={schemaVersion:1,artifactKind:"datapack-promotion-request",candidate:component,compatibilityEvidenceSha256:sha(compatibility),requestedBy:"AquilaXk",approval:{workflowRunId:"123",environment:"datapack-promotion",reviewer:"AquilaXk",approvalEvidenceSha256:sha(approval)},contractVersion:"datapack-promotion-v1",issueRef:"AquilaXk/easysubway#2699"};const put=(n,v)=>{const p=path.join(root,n);writeFileSync(p,v);return p;};return{request,requestBytes:JSON.stringify(request),requestPath:put("request.json",JSON.stringify(request)),componentPath:put("component.json",JSON.stringify(component)),inventoryPath:put("inventory.json",ib),compatibilityPath:put("compatibility.json",compatibility),approvalPath:put("approval.json",approval),cleanup:()=>rmSync(root,{recursive:true,force:true})};}
function run(f){return spawnSync(process.execPath,[script,"--request",f.requestPath,"--component",f.componentPath,"--inventory",f.inventoryPath,"--compatibility-evidence",f.compatibilityPath,"--approval-evidence",f.approvalPath],{encoding:"utf8"});}
