CREATE TABLE admin_users (
    login_id VARCHAR(120) NOT NULL PRIMARY KEY,
    display_name VARCHAR(120) NOT NULL,
    email VARCHAR(255),
    password_hash VARCHAR(255) NOT NULL,
    auth_method VARCHAR(40) NOT NULL,
    role VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL,
    failed_login_count INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMP,
    password_changed_at TIMESTAMP NOT NULL,
    password_expires_at TIMESTAMP,
    credential_rotation_required BOOLEAN NOT NULL DEFAULT FALSE,
    break_glass_reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE admin_login_audits (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id VARCHAR(120) NOT NULL,
    auth_method VARCHAR(40) NOT NULL,
    outcome VARCHAR(40) NOT NULL,
    reason VARCHAR(500),
    occurred_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_admin_login_audits_login_occurred_at
    ON admin_login_audits (login_id, occurred_at);
